# Generated by Django 6.0.4 on 2026-06-11 14:38

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IceCream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('recommended_price', models.IntegerField(validators=[core.models.validate_positive])),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('kind', models.CharField(choices=[('ge', 'Gelato'), ('fc', 'Frozen Custard'), ('ss', 'Soft Serve'), ('fy', 'Frozen Yogurt'), ('sh', 'Sherbet'), ('ri', 'Rolled Ice Cream')], default='ss', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Kiosk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(validators=[core.models.validate_positive])),
            ],
        ),
        migrations.CreateModel(
            name='KioskIceCream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantity', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('icecream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.icecream')),
                ('kiosk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kiosk')),
            ],
        ),
        migrations.AddField(
            model_name='kiosk',
            name='icecreams',
            field=models.ManyToManyField(through='core.KioskIceCream', to='core.icecream'),
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(validators=[core.models.validate_positive])),
                ('favorite_icecream', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.icecream')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.person')),
            ],
        ),
    ]
