# Generated by Django 6.0.4 on 2026-04-27 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.person'),
        ),
        migrations.AddField(
            model_name='kiosk',
            name='icecreams',
            field=models.ManyToManyField(to='core.icecream'),
        ),
    ]
