# Generated by Django 6.0.4 on 2026-06-17 11:09

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.person')),
                ('hire_date', models.DateField()),
            ],
            bases=('core.person',),
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.employee')),
                ('education', models.CharField(choices=[('sc', 'Среднее'), ('sp', 'Среднее специальное'), ('he', 'Высшее')], default='he', max_length=2)),
                ('grade', models.IntegerField(default=1, validators=[core.models.validate_positive])),
            ],
            bases=('core.employee',),
        ),
    ]
