# Generated by Django 6.0.4 on 2026-04-28 12:53

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_child_parent_kiosk_icecreams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='age',
            field=models.IntegerField(validators=[core.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='child',
            name='favorite_icecream',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.icecream'),
        ),
        migrations.AlterField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.person'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='icecream',
            name='price',
            field=models.IntegerField(validators=[core.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(validators=[core.models.validate_positive]),
        ),
    ]
