# Generated by Django 6.0.4 on 2026-05-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_child_age_alter_child_favorite_icecream_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='icecream',
            name='kind',
            field=models.CharField(choices=[('ge', 'Gelato'), ('fc', 'Frozen Custard'), ('ss', 'Soft Serve'), ('fy', 'Frozen Yogurt'), ('sh', 'Sherbet'), ('ri', 'Rolled Ice Cream')], default='ss', max_length=2),
        ),
    ]
