# Generated by Django 6.0.4 on 2026-06-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_icecream_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='icecream',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
